### ISSUE TITLE
Special foreign characters are not supported

### ISSUE THREAD

**Issue by newluck77** [danielegobbetti/ICSImport#9]
Hello,

I wanted to import a [calendar entry](http://kalender.kjwien.at/site/calendar_list_month.siteswift?so=site_calendar&do=all&c=vcal&d=calendar%3A1200) from a German speaking webpage, which contains "Büro". 

This is the Log I fetched:

    03-09 09:47:55.931 E/ICS-Import(2409): error processing file:///storage/emulated/0/Download/calendar(8).ics : net.fortuna.ical4j.data.ParserException: Error at line 13:Illegal property [ BÜRO]

I hope you can fix this.

**Comment by danielegobbetti** [comment]
I believe it's fixed in release 1.3.

**Comment by StefanBrand** [comment]
After a fast check I still get "Invalid ICS file" for a calendar entry with a location field of "Mödling".
